# Generated by Django 5.2.4 on 2025-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animefan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=20)),
                ('Lastname', models.CharField(default='', max_length=20)),
                ('Username', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
