# Generated by Django 5.2.7 on 2025-11-04 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animevideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anime_name', models.CharField(max_length=200)),
                ('Anime_poster', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Anime_wallpaper', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Anime_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Anime_description', models.TextField(max_length=500)),
            ],
        ),
    ]
