# Generated by Django 5.2.7 on 2025-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0002_animevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='Anime_category',
            field=models.CharField(choices=[('TN', 'Tamil Nadu'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra')], default='TN', max_length=2),
            preserve_default=False,
        ),
    ]
