# Generated by Django 5.2.7 on 2025-11-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0003_animevideo_anime_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creater_id', models.CharField(max_length=20)),
                ('Password_cr', models.CharField(max_length=10)),
                ('Email_cr', models.EmailField(default='', max_length=254)),
                ('login_time', models.TimeField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_category',
            field=models.CharField(choices=[('CO', 'Comady'), ('MI', 'Mistery'), ('LO', 'Love'), ('DA', 'Drama'), ('ST', 'Sport')], max_length=2),
        ),
    ]
