# Generated by Django 5.2.7 on 2025-11-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0004_creatorid_alter_animevideo_anime_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorid',
            old_name='Creater_id',
            new_name='Creator_id',
        ),
    ]
