# Generated by Django 5.2.7 on 2025-11-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0005_rename_creater_id_creatorid_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_category',
            field=models.CharField(choices=[('CO', 'Comedy'), ('MY', 'Mystery'), ('LO', 'Love'), ('DR', 'Drama'), ('SP', 'Sport')], max_length=2),
        ),
    ]
