# Generated by Django 5.2.7 on 2025-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0006_alter_animevideo_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_category',
            field=models.CharField(choices=[('CO', 'Comedy'), ('MY', 'Mystery'), ('LO', 'Love'), ('DR', 'Drama'), ('SP', 'Sport')], max_length=20),
        ),
    ]
