# Generated by Django 5.2.7 on 2025-11-07 18:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0007_alter_animevideo_anime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tl', 'Tamil'), ('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('te', 'Telugu'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese (Mandarin)'), ('yue', 'Chinese (Cantonese)'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('id', 'Indonesian'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('bn', 'Bengali'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('fa', 'Persian'), ('ms', 'Malay'), ('ne', 'Nepali'), ('si', 'Sinhala'), ('sw', 'Swahili'), ('ta', 'Tagalog'), ('ro', 'Romanian'), ('nl', 'Dutch'), ('he', 'Hebrew'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('da', 'Danish'), ('fi', 'Finnish')], default=['en'], max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CO', 'Comedy'), ('MY', 'Mystery'), ('LO', 'Love'), ('DR', 'Drama'), ('SP', 'Sport'), ('AC', 'Action'), ('FA', 'Fantasy'), ('AD', 'Adventure'), ('HR', 'Horror'), ('SF', 'Sci-Fi')], max_length=200),
        ),
    ]
