# Generated by Django 5.2.7 on 2025-11-07 19:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0008_animevideo_language_alter_animevideo_anime_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animevideo',
            name='language',
        ),
        migrations.AddField(
            model_name='animevideo',
            name='Language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tl', 'Tamil'), ('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('te', 'Telugu'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese (Mandarin)'), ('yue', 'Chinese (Cantonese)'), ('fr', 'French'), ('es', 'Spanish')], default=['en'], max_length=200),
            preserve_default=False,
        ),
    ]
