# Generated by Django 5.2.7 on 2025-11-08 05:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0009_remove_animevideo_language_animevideo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='Language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tl', 'Tamil'), ('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('te', 'Telugu'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese (Mandarin)'), ('yu', 'Chinese (Cantonese)'), ('fr', 'French'), ('es', 'Spanish')], default=['en'], max_length=200),
        ),
    ]
