# Generated by Django 5.2.7 on 2025-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0010_alter_animevideo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_poster',
            field=models.ImageField(blank=True, null=True, upload_to='anime_posters/'),
        ),
    ]
