# Generated by Django 5.2.7 on 2025-11-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0012_likedanime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedAnime',
        ),
    ]
