# Generated by Django 5.2.7 on 2025-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0013_delete_likedanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
