# Generated by Django 5.2.7 on 2025-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0014_animevideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='like',
            field=models.IntegerField(default=''),
        ),
    ]
