# Generated by Django 5.2.7 on 2025-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0015_alter_animevideo_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animevideo',
            name='like',
        ),
        migrations.AddField(
            model_name='animevideo',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_animes', to='tailfox.animefan'),
        ),
    ]
