# Generated by Django 5.2.7 on 2025-11-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0016_remove_animevideo_like_animevideo_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animevideo',
            old_name='like_users',
            new_name='like',
        ),
    ]
