# Generated by Django 5.2.7 on 2025-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0017_rename_like_users_animevideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_animes', to='tailfox.animefan'),
        ),
    ]
