# Generated by Django 5.2.7 on 2025-11-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0018_alter_animevideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_animes', to='tailfox.animefan'),
        ),
    ]
