# Generated by Django 5.2.7 on 2025-11-24 06:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0019_alter_animevideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='Anime_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Comedy', 'Comedy'), ('MYSTERY', 'Mystery'), ('LOVE', 'Love'), ('DRAMA', 'Drama'), ('SPORT', 'Sport'), ('ACTION', 'Action'), ('FANTASY', 'Fantasy'), ('ADVENTURE', 'Adventure'), ('HORROR', 'Horror'), ('SCI-FI', 'Sci-Fi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='animevideo',
            name='Language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Chinese', 'Chinese'), ('French', 'French'), ('Spanish', 'Spanish')], default=['en'], max_length=200),
        ),
    ]
