# Generated by Django 5.2.7 on 2025-11-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailfox.animevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailfox.animefan')),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
