# Generated by Django 5.2.7 on 2025-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0022_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='animefan',
            name='Profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
