# Generated by Django 5.2.7 on 2025-11-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0023_animefan_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=255)),
                ('anime_video', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tailfox.animevideo')),
            ],
        ),
    ]
