# Generated by Django 5.2.7 on 2025-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0024_animeepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='anime_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='AnimeEpisode',
        ),
    ]
