# Generated by Django 5.2.7 on 2025-11-24 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0025_animevideo_anime_video_delete_animeepisode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animevideo',
            name='anime_video',
        ),
        migrations.CreateModel(
            name='AnimeVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tailfox.animevideo')),
            ],
        ),
    ]
