# Generated by Django 5.2.7 on 2025-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0026_remove_animevideo_anime_video_animevideofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
