# Generated by Django 5.2.7 on 2025-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0027_animevideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animevideo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
