# Generated by Django 5.2.7 on 2025-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0028_alter_animevideo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animevideo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='animevideofile',
            name='video',
        ),
        migrations.AddField(
            model_name='animevideofile',
            name='episode_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animevideofile',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animevideofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animevideofile',
            name='video_file',
            field=models.FileField(default='', upload_to='anime_videos/'),
            preserve_default=False,
        ),
    ]
