# Generated by Django 5.2.7 on 2025-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0029_remove_animevideo_slug_remove_animevideofile_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
