# Generated by Django 5.2.7 on 2025-11-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0031_alter_animevideo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideo',
            name='video_file',
            field=models.FileField(default='', upload_to='anime_videos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnimeVideoFile',
        ),
    ]
