# Generated by Django 5.2.7 on 2025-11-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0032_animevideo_video_file_delete_animevideofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('episode_name', models.CharField(blank=True, max_length=200, null=True)),
                ('video_file', models.FileField(upload_to='anime_videos/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tailfox.animevideo')),
            ],
        ),
    ]
