# Generated by Django 5.2.7 on 2025-11-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0033_animevideofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animevideo',
            name='video_file',
        ),
    ]
