# Generated by Django 5.2.8 on 2025-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0034_remove_animevideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideofile',
            name='episode_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
