# Generated by Django 5.2.8 on 2025-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailfox', '0035_animevideofile_episode_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevideofile',
            name='anime_sesion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
